import React from 'react';
import { useCurrentFrame, useVideoConfig } from 'remotion';

/**
 * Fallback component: Background
 * Auto-generated by AI Agent when AI generation fails
 */
export const Background: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();

  const opacity = Math.min(1, frame / 30);
  const scale = 1 + Math.sin(frame / 20) * 0.1;

  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 64,
        fontWeight: 'bold',
        color: 'white',
        opacity,
        transform: `scale(${scale})`,
        backgroundColor: '#1a1a2e',
        width: '100%',
        height: '100%',
      }}
    >
      A 10-second test video featuring animated text
    </div>
  );
};