import React from 'react';
import { useCurrentFrame, useVideoConfig } from 'remotion';

/**
 * Fallback component: KontrasScene
 * Auto-generated by AI Agent for 4K 60fps seamless loop
 * Technology background animation
 */
export const KontrasScene: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();

  // Seamless loop calculation
  const loopFrame = frame % durationInFrames;
  const progress = loopFrame / durationInFrames;

  // Complex technology animation parameters
  const opacity = 0.5 + Math.sin(progress * Math.PI * 2) * 0.3;
  const scale = 1 + Math.sin(progress * Math.PI * 4) * 0.15;
  const rotation = progress * 360;
  const hue = (progress * 360) % 360;

  // Grid pattern for technology theme
  const gridSize = 50;
  const gridOffset = (loopFrame * 2) % gridSize;

  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 48,
        fontWeight: 'bold',
        color: `hsl(${hue}, 70%, 60%)`,
        opacity,
        transform: `scale(${scale}) rotate(${rotation}deg)`,
        backgroundColor: '#0a0a1a',
        width: '100%',
        height: '100%',
        position: 'relative',
        overflow: 'hidden',
      }}
    >
      {/* Technology grid background */}
      <div
        style={{
          position: 'absolute',
          top: -gridOffset,
          left: -gridOffset,
          right: -gridOffset,
          bottom: -gridOffset,
          backgroundImage: `
            linear-gradient(rgba(0, 255, 255, 0.1) 1px, transparent 1px),
            linear-gradient(90deg, rgba(0, 255, 255, 0.1) 1px, transparent 1px)
          `,
          backgroundSize: `${gridSize}px ${gridSize}px`,
          animation: 'gridMove 2s linear infinite',
        }}
      />
      
      {/* Animated particles */}
      {[...Array(20)].map((_, i) => (
        <div
          key={i}
          style={{
            position: 'absolute',
            width: 4,
            height: 4,
            backgroundColor: `hsl(${(hue + i * 18) % 360}, 80%, 60%)`,
            borderRadius: '50%',
            left: `${50 + Math.sin(progress * Math.PI * 2 + i) * 40}%`,
            top: `${50 + Math.cos(progress * Math.PI * 2 + i) * 40}%`,
            opacity: 0.8,
            boxShadow: `0 0 10px hsl(${(hue + i * 18) % 360}, 80%, 60%)`,
          }}
        />
      ))}

      {/* Main content */}
      <div style={{ position: 'relative', zIndex: 1, textShadow: '0 0 20px currentColor' }}>
        Menggambarkan kehidupan sederhana di era modern
      </div>

      <style>{`
        @keyframes gridMove {
          0% { transform: translate(0, 0); }
          100% { transform: translate(${gridSize}px, ${gridSize}px); }
        }
      `}</style>
    </div>
  );
};